print("Class Seating")


def stadiumpro():
    while True:
        #Prices of each class of ticket
      Class_A = 20
      Class_B = 15
      Class_C = 10
     
      strt = input("Would you like to start class seating program? y/n: ").lower()
      
      if strt != "y":
       print("This program has concluded. Please restart to begin program and enter y at prompt.")
       break
   #User enters number of tickets sold for each class

      Class_A_tot = int(input("Enter amount of Class A tickets the Stadium sold (whole numbers only): "))
      Class_B_tot = int(input("Enter amount of Class B tickets the Stadium sold (whole numbers only): "))
      Class_C_tot = int(input("Enter amount of Class C tickets the Stadium sold (whole numbers only): "))

      tickets_sold = Class_A_tot + Class_B_tot + Class_C_tot
      ticket_profit = (Class_A * Class_A_tot) + (Class_B * Class_B_tot) + (Class_C * Class_C_tot)

      #Output of number of tickets sold and income generated 
      print(f"Tickets Sold: {tickets_sold}\n Income Generated by Stadium: ${ticket_profit:.2f}")
      
stadiumpro()